<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PhotoOrganizer.Platform.Abstractions\PhotoOrganizer.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\PhotoOrganizer.Domain\PhotoOrganizer.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpHook" Version="7.1.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
